/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_timeface_scanner_cv_OpenCVManager */

#ifndef _Included_com_timeface_scanner_cv_OpenCVManager
#define _Included_com_timeface_scanner_cv_OpenCVManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_timeface_scanner_cv_OpenCVManager
 * Method:    nScan
 * Signature: (Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_timeface_scanner_cv_OpenCVManager_nScan
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_timeface_scanner_cv_OpenCVManager
 * Method:    nCrop
 * Signature: (Ljava/lang/String;[[I)V
 */
JNIEXPORT void JNICALL Java_com_timeface_scanner_cv_OpenCVManager_nCrop
  (JNIEnv *, jclass, jstring, jobjectArray, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
